export enum CONVERSATION_STATUS {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  SNOOZED = 'SNOOZED',
}
export enum CONVERSATION_TYPE {
  GROUP = 'GROUP',
  COLABORATION = 'COLABORATON',
  SINGLE = 'SINGLE',
}
export enum CONVERSATION_CHANNEL {
  CHAT = 'CHAT',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  MESSENGER = 'MESSENGER',
}

export enum ATTACHMENT_TYPE {
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  FILE = 'FILE',
  CODE_SNIPPET = 'CODE_SNIPPET',
  STICKER = 'STICKER',
  IMAGE = 'IMAGE',
}
export enum MESSAGE_TYPE {
  ARTICLE = 'ARTICLE',
  NOTE = 'NOTE',
  TEXT = 'TEXT',
  INFO = 'INFO',
  WARNING = 'WARNING',
  PROMPT = 'PROMPT',
  SURVEY_ANSWER = 'SURVEY_ANSWER',
  REPLY = 'REPLY',
  SWITCH_TO_AGENT = 'SWITCH_TO_AGENT',
  SWITCH_TO_BOT = 'SWITCH_TO_BOT',
}

export enum PROMPT_TYPE {
  EMAIL = 'EMAIL',
}

export enum EMAIL_REQUIRED_STATUS {
  OFFICE_HOURS = 'OFFICE_HOURS',
  ALWAYS = 'ALWAYS',
  NEVER = 'NEVER',
}